// Code generated by gen-accessors; DO NOT EDIT.

package layer

// GetAutoOrient returns the AutoOrient field if it's non-nil, zero value otherwise.
func (i *ImageT) GetAutoOrient() int {
	if i == nil || i.AutoOrient == nil {
		return 0
	}
	return *i.AutoOrient
}

// GetBlendMode returns the BlendMode field if it's non-nil, zero value otherwise.
func (i *ImageT) GetBlendMode() int {
	if i == nil || i.BlendMode == nil {
		return 0
	}
	return *i.BlendMode
}

// GetClass returns the Class field if it's non-nil, zero value otherwise.
func (i *ImageT) GetClass() string {
	if i == nil || i.Class == nil {
		return ""
	}
	return *i.Class
}

// GetDdd returns the Ddd field if it's non-nil, zero value otherwise.
func (i *ImageT) GetDdd() int {
	if i == nil || i.Ddd == nil {
		return 0
	}
	return *i.Ddd
}

// GetHasMask returns the HasMask field if it's non-nil, zero value otherwise.
func (i *ImageT) GetHasMask() bool {
	if i == nil || i.HasMask == nil {
		return false
	}
	return *i.HasMask
}

// GetInded returns the Inded field if it's non-nil, zero value otherwise.
func (i *ImageT) GetInded() int {
	if i == nil || i.Inded == nil {
		return 0
	}
	return *i.Inded
}

// GetInPoint returns the InPoint field if it's non-nil, zero value otherwise.
func (i *ImageT) GetInPoint() float64 {
	if i == nil || i.InPoint == nil {
		return 0.0
	}
	return *i.InPoint
}

// GetLayerName returns the LayerName field if it's non-nil, zero value otherwise.
func (i *ImageT) GetLayerName() string {
	if i == nil || i.LayerName == nil {
		return ""
	}
	return *i.LayerName
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (i *ImageT) GetName() string {
	if i == nil || i.Name == nil {
		return ""
	}
	return *i.Name
}

// GetOutPoint returns the OutPoint field if it's non-nil, zero value otherwise.
func (i *ImageT) GetOutPoint() float64 {
	if i == nil || i.OutPoint == nil {
		return 0.0
	}
	return *i.OutPoint
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (i *ImageT) GetParent() int {
	if i == nil || i.Parent == nil {
		return 0
	}
	return *i.Parent
}

// GetRefID returns the RefID field if it's non-nil, zero value otherwise.
func (i *ImageT) GetRefID() string {
	if i == nil || i.RefID == nil {
		return ""
	}
	return *i.RefID
}

// GetStartTime returns the StartTime field if it's non-nil, zero value otherwise.
func (i *ImageT) GetStartTime() float64 {
	if i == nil || i.StartTime == nil {
		return 0.0
	}
	return *i.StartTime
}

// GetTimeStretching returns the TimeStretching field if it's non-nil, zero value otherwise.
func (i *ImageT) GetTimeStretching() float64 {
	if i == nil || i.TimeStretching == nil {
		return 0.0
	}
	return *i.TimeStretching
}

// GetAutoOrient returns the AutoOrient field if it's non-nil, zero value otherwise.
func (n *NullT) GetAutoOrient() int {
	if n == nil || n.AutoOrient == nil {
		return 0
	}
	return *n.AutoOrient
}

// GetClass returns the Class field if it's non-nil, zero value otherwise.
func (n *NullT) GetClass() string {
	if n == nil || n.Class == nil {
		return ""
	}
	return *n.Class
}

// GetDdd returns the Ddd field if it's non-nil, zero value otherwise.
func (n *NullT) GetDdd() int {
	if n == nil || n.Ddd == nil {
		return 0
	}
	return *n.Ddd
}

// GetInd returns the Ind field if it's non-nil, zero value otherwise.
func (n *NullT) GetInd() int {
	if n == nil || n.Ind == nil {
		return 0
	}
	return *n.Ind
}

// GetInPoint returns the InPoint field if it's non-nil, zero value otherwise.
func (n *NullT) GetInPoint() float64 {
	if n == nil || n.InPoint == nil {
		return 0.0
	}
	return *n.InPoint
}

// GetLayerName returns the LayerName field if it's non-nil, zero value otherwise.
func (n *NullT) GetLayerName() string {
	if n == nil || n.LayerName == nil {
		return ""
	}
	return *n.LayerName
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (n *NullT) GetName() float64 {
	if n == nil || n.Name == nil {
		return 0.0
	}
	return *n.Name
}

// GetOutPoint returns the OutPoint field if it's non-nil, zero value otherwise.
func (n *NullT) GetOutPoint() float64 {
	if n == nil || n.OutPoint == nil {
		return 0.0
	}
	return *n.OutPoint
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (n *NullT) GetParent() int {
	if n == nil || n.Parent == nil {
		return 0
	}
	return *n.Parent
}

// GetStartTime returns the StartTime field if it's non-nil, zero value otherwise.
func (n *NullT) GetStartTime() float64 {
	if n == nil || n.StartTime == nil {
		return 0.0
	}
	return *n.StartTime
}

// GetTimeStretching returns the TimeStretching field if it's non-nil, zero value otherwise.
func (n *NullT) GetTimeStretching() float64 {
	if n == nil || n.TimeStretching == nil {
		return 0.0
	}
	return *n.TimeStretching
}

// GetAutoOrient returns the AutoOrient field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetAutoOrient() int {
	if p == nil || p.AutoOrient == nil {
		return 0
	}
	return *p.AutoOrient
}

// GetBlendMode returns the BlendMode field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetBlendMode() int {
	if p == nil || p.BlendMode == nil {
		return 0
	}
	return *p.BlendMode
}

// GetClass returns the Class field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetClass() string {
	if p == nil || p.Class == nil {
		return ""
	}
	return *p.Class
}

// GetDdd returns the Ddd field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetDdd() int {
	if p == nil || p.Ddd == nil {
		return 0
	}
	return *p.Ddd
}

// GetHasMask returns the HasMask field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetHasMask() bool {
	if p == nil || p.HasMask == nil {
		return false
	}
	return *p.HasMask
}

// GetIndex returns the Index field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetIndex() int {
	if p == nil || p.Index == nil {
		return 0
	}
	return *p.Index
}

// GetInPoint returns the InPoint field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetInPoint() float64 {
	if p == nil || p.InPoint == nil {
		return 0.0
	}
	return *p.InPoint
}

// GetLayerName returns the LayerName field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetLayerName() string {
	if p == nil || p.LayerName == nil {
		return ""
	}
	return *p.LayerName
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetName() string {
	if p == nil || p.Name == nil {
		return ""
	}
	return *p.Name
}

// GetOutPoint returns the OutPoint field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetOutPoint() float64 {
	if p == nil || p.OutPoint == nil {
		return 0.0
	}
	return *p.OutPoint
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetParent() int {
	if p == nil || p.Parent == nil {
		return 0
	}
	return *p.Parent
}

// GetRefID returns the RefID field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetRefID() string {
	if p == nil || p.RefID == nil {
		return ""
	}
	return *p.RefID
}

// GetStartTime returns the StartTime field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetStartTime() float64 {
	if p == nil || p.StartTime == nil {
		return 0.0
	}
	return *p.StartTime
}

// GetTimeMapping returns the TimeMapping field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetTimeMapping() float64 {
	if p == nil || p.TimeMapping == nil {
		return 0.0
	}
	return *p.TimeMapping
}

// GetTimeStretching returns the TimeStretching field if it's non-nil, zero value otherwise.
func (p *PreCompT) GetTimeStretching() float64 {
	if p == nil || p.TimeStretching == nil {
		return 0.0
	}
	return *p.TimeStretching
}

// GetAutoOrient returns the AutoOrient field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetAutoOrient() int {
	if s == nil || s.AutoOrient == nil {
		return 0
	}
	return *s.AutoOrient
}

// GetBlendMode returns the BlendMode field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetBlendMode() int {
	if s == nil || s.BlendMode == nil {
		return 0
	}
	return *s.BlendMode
}

// GetClass returns the Class field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetClass() string {
	if s == nil || s.Class == nil {
		return ""
	}
	return *s.Class
}

// GetDdd returns the Ddd field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetDdd() int {
	if s == nil || s.Ddd == nil {
		return 0
	}
	return *s.Ddd
}

// GetHasMask returns the HasMask field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetHasMask() bool {
	if s == nil || s.HasMask == nil {
		return false
	}
	return *s.HasMask
}

// GetIndex returns the Index field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetIndex() int {
	if s == nil || s.Index == nil {
		return 0
	}
	return *s.Index
}

// GetInPoint returns the InPoint field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetInPoint() float64 {
	if s == nil || s.InPoint == nil {
		return 0.0
	}
	return *s.InPoint
}

// GetLayerName returns the LayerName field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetLayerName() string {
	if s == nil || s.LayerName == nil {
		return ""
	}
	return *s.LayerName
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetName() string {
	if s == nil || s.Name == nil {
		return ""
	}
	return *s.Name
}

// GetOutPoint returns the OutPoint field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetOutPoint() float64 {
	if s == nil || s.OutPoint == nil {
		return 0.0
	}
	return *s.OutPoint
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetParent() int {
	if s == nil || s.Parent == nil {
		return 0
	}
	return *s.Parent
}

// GetStartTime returns the StartTime field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetStartTime() float64 {
	if s == nil || s.StartTime == nil {
		return 0.0
	}
	return *s.StartTime
}

// GetTimeStretching returns the TimeStretching field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetTimeStretching() float64 {
	if s == nil || s.TimeStretching == nil {
		return 0.0
	}
	return *s.TimeStretching
}
