// Code generated by gen-accessors; DO NOT EDIT.

package layer

// GetAo returns the Ao field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetAo() int {
	if s == nil || s.Ao == nil {
		return 0
	}
	return *s.Ao
}

// GetBm returns the Bm field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetBm() int {
	if s == nil || s.Bm == nil {
		return 0
	}
	return *s.Bm
}

// GetCl returns the Cl field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetCl() string {
	if s == nil || s.Cl == nil {
		return ""
	}
	return *s.Cl
}

// GetDdd returns the Ddd field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetDdd() int {
	if s == nil || s.Ddd == nil {
		return 0
	}
	return *s.Ddd
}

// GetHasMask returns the HasMask field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetHasMask() bool {
	if s == nil || s.HasMask == nil {
		return false
	}
	return *s.HasMask
}

// GetInd returns the Ind field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetInd() int {
	if s == nil || s.Ind == nil {
		return 0
	}
	return *s.Ind
}

// GetIp returns the Ip field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetIp() int {
	if s == nil || s.Ip == nil {
		return 0
	}
	return *s.Ip
}

// GetLn returns the Ln field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetLn() string {
	if s == nil || s.Ln == nil {
		return ""
	}
	return *s.Ln
}

// GetNm returns the Nm field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetNm() string {
	if s == nil || s.Nm == nil {
		return ""
	}
	return *s.Nm
}

// GetOp returns the Op field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetOp() int {
	if s == nil || s.Op == nil {
		return 0
	}
	return *s.Op
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetParent() int {
	if s == nil || s.Parent == nil {
		return 0
	}
	return *s.Parent
}

// GetSr returns the Sr field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetSr() float64 {
	if s == nil || s.Sr == nil {
		return 0.0
	}
	return *s.Sr
}

// GetSt returns the St field if it's non-nil, zero value otherwise.
func (s *ShapeT) GetSt() float64 {
	if s == nil || s.St == nil {
		return 0.0
	}
	return *s.St
}
