// Code generated by gen-accessors; DO NOT EDIT.

package flare

// GetAnimationEnd returns the AnimationEnd field if it's non-nil, zero value otherwise.
func (a *Animation) GetAnimationEnd() float64 {
	if a == nil || a.AnimationEnd == nil {
		return 0.0
	}
	return *a.AnimationEnd
}

// GetAnimationStart returns the AnimationStart field if it's non-nil, zero value otherwise.
func (a *Animation) GetAnimationStart() float64 {
	if a == nil || a.AnimationStart == nil {
		return 0.0
	}
	return *a.AnimationStart
}

// GetDuration returns the Duration field if it's non-nil, zero value otherwise.
func (a *Animation) GetDuration() float64 {
	if a == nil || a.Duration == nil {
		return 0.0
	}
	return *a.Duration
}

// GetFPS returns the FPS field if it's non-nil, zero value otherwise.
func (a *Animation) GetFPS() float64 {
	if a == nil || a.FPS == nil {
		return 0.0
	}
	return *a.FPS
}

// GetIsLooping returns the IsLooping field if it's non-nil, zero value otherwise.
func (a *Animation) GetIsLooping() bool {
	if a == nil || a.IsLooping == nil {
		return false
	}
	return *a.IsLooping
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (a *Animation) GetName() string {
	if a == nil || a.Name == nil {
		return ""
	}
	return *a.Name
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (a *Animation) GetType() string {
	if a == nil || a.Type == nil {
		return ""
	}
	return *a.Type
}

// GetClipContents returns the ClipContents field if it's non-nil, zero value otherwise.
func (a *Artboard) GetClipContents() bool {
	if a == nil || a.ClipContents == nil {
		return false
	}
	return *a.ClipContents
}

// GetColor returns the Color field.
func (a *Artboard) GetColor() *Color {
	if a == nil {
		return nil
	}
	return a.Color
}

// GetHeight returns the Height field if it's non-nil, zero value otherwise.
func (a *Artboard) GetHeight() float64 {
	if a == nil || a.Height == nil {
		return 0.0
	}
	return *a.Height
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (a *Artboard) GetName() string {
	if a == nil || a.Name == nil {
		return ""
	}
	return *a.Name
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (a *Artboard) GetType() string {
	if a == nil || a.Type == nil {
		return ""
	}
	return *a.Type
}

// GetWidth returns the Width field if it's non-nil, zero value otherwise.
func (a *Artboard) GetWidth() float64 {
	if a == nil || a.Width == nil {
		return 0.0
	}
	return *a.Width
}

// GetComponent returns the Component field if it's non-nil, zero value otherwise.
func (k *Key) GetComponent() int {
	if k == nil || k.Component == nil {
		return 0
	}
	return *k.Component
}

// GetCubicX1 returns the CubicX1 field if it's non-nil, zero value otherwise.
func (k *KeyNode) GetCubicX1() float64 {
	if k == nil || k.CubicX1 == nil {
		return 0.0
	}
	return *k.CubicX1
}

// GetCubicX2 returns the CubicX2 field if it's non-nil, zero value otherwise.
func (k *KeyNode) GetCubicX2() float64 {
	if k == nil || k.CubicX2 == nil {
		return 0.0
	}
	return *k.CubicX2
}

// GetCubicY1 returns the CubicY1 field if it's non-nil, zero value otherwise.
func (k *KeyNode) GetCubicY1() float64 {
	if k == nil || k.CubicY1 == nil {
		return 0.0
	}
	return *k.CubicY1
}

// GetCubicY2 returns the CubicY2 field if it's non-nil, zero value otherwise.
func (k *KeyNode) GetCubicY2() float64 {
	if k == nil || k.CubicY2 == nil {
		return 0.0
	}
	return *k.CubicY2
}

// GetInterpolatorType returns the InterpolatorType field.
func (k *KeyNode) GetInterpolatorType() *InterpolatorType {
	if k == nil {
		return nil
	}
	return k.InterpolatorType
}

// GetTime returns the Time field if it's non-nil, zero value otherwise.
func (k *KeyNode) GetTime() float64 {
	if k == nil || k.Time == nil {
		return 0.0
	}
	return *k.Time
}

// GetBlendMode returns the BlendMode field.
func (n *Node) GetBlendMode() *BlendModeType {
	if n == nil {
		return nil
	}
	return n.BlendMode
}

// GetCap returns the Cap field if it's non-nil, zero value otherwise.
func (n *Node) GetCap() float64 {
	if n == nil || n.Cap == nil {
		return 0.0
	}
	return *n.Cap
}

// GetClips returns the Clips field if it's non-nil, zero value otherwise.
func (n *Node) GetClips() []int {
	if n == nil || n.Clips == nil {
		return nil
	}
	return *n.Clips
}

// GetColor returns the Color field.
func (n *Node) GetColor() *Color {
	if n == nil {
		return nil
	}
	return n.Color
}

// GetDrawOrder returns the DrawOrder field if it's non-nil, zero value otherwise.
func (n *Node) GetDrawOrder() int {
	if n == nil || n.DrawOrder == nil {
		return 0
	}
	return *n.DrawOrder
}

// GetFillRule returns the FillRule field if it's non-nil, zero value otherwise.
func (n *Node) GetFillRule() int {
	if n == nil || n.FillRule == nil {
		return 0
	}
	return *n.FillRule
}

// GetHeight returns the Height field if it's non-nil, zero value otherwise.
func (n *Node) GetHeight() float64 {
	if n == nil || n.Height == nil {
		return 0.0
	}
	return *n.Height
}

// GetIsClosed returns the IsClosed field if it's non-nil, zero value otherwise.
func (n *Node) GetIsClosed() bool {
	if n == nil || n.IsClosed == nil {
		return false
	}
	return *n.IsClosed
}

// GetIsCollapsed returns the IsCollapsed field if it's non-nil, zero value otherwise.
func (n *Node) GetIsCollapsed() bool {
	if n == nil || n.IsCollapsed == nil {
		return false
	}
	return *n.IsCollapsed
}

// GetIsVisible returns the IsVisible field if it's non-nil, zero value otherwise.
func (n *Node) GetIsVisible() bool {
	if n == nil || n.IsVisible == nil {
		return false
	}
	return *n.IsVisible
}

// GetJoin returns the Join field if it's non-nil, zero value otherwise.
func (n *Node) GetJoin() float64 {
	if n == nil || n.Join == nil {
		return 0.0
	}
	return *n.Join
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (n *Node) GetName() string {
	if n == nil || n.Name == nil {
		return ""
	}
	return *n.Name
}

// GetNumColorStops returns the NumColorStops field if it's non-nil, zero value otherwise.
func (n *Node) GetNumColorStops() int {
	if n == nil || n.NumColorStops == nil {
		return 0
	}
	return *n.NumColorStops
}

// GetOpacity returns the Opacity field if it's non-nil, zero value otherwise.
func (n *Node) GetOpacity() float64 {
	if n == nil || n.Opacity == nil {
		return 0.0
	}
	return *n.Opacity
}

// GetParent returns the Parent field if it's non-nil, zero value otherwise.
func (n *Node) GetParent() int {
	if n == nil || n.Parent == nil {
		return 0
	}
	return *n.Parent
}

// GetRotation returns the Rotation field if it's non-nil, zero value otherwise.
func (n *Node) GetRotation() float64 {
	if n == nil || n.Rotation == nil {
		return 0.0
	}
	return *n.Rotation
}

// GetSecondaryRadiusScale returns the SecondaryRadiusScale field if it's non-nil, zero value otherwise.
func (n *Node) GetSecondaryRadiusScale() float64 {
	if n == nil || n.SecondaryRadiusScale == nil {
		return 0.0
	}
	return *n.SecondaryRadiusScale
}

// GetTrim returns the Trim field if it's non-nil, zero value otherwise.
func (n *Node) GetTrim() float64 {
	if n == nil || n.Trim == nil {
		return 0.0
	}
	return *n.Trim
}

// GetType returns the Type field.
func (n *Node) GetType() *NodeType {
	if n == nil {
		return nil
	}
	return n.Type
}

// GetWidth returns the Width field if it's non-nil, zero value otherwise.
func (n *Node) GetWidth() float64 {
	if n == nil || n.Width == nil {
		return 0.0
	}
	return *n.Width
}

// GetPointType returns the PointType field.
func (p *Point) GetPointType() *PointType {
	if p == nil {
		return nil
	}
	return p.PointType
}

// GetRadius returns the Radius field if it's non-nil, zero value otherwise.
func (p *Point) GetRadius() float64 {
	if p == nil || p.Radius == nil {
		return 0.0
	}
	return *p.Radius
}

// GetVersion returns the Version field if it's non-nil, zero value otherwise.
func (r *Root) GetVersion() int {
	if r == nil || r.Version == nil {
		return 0
	}
	return *r.Version
}
