// Code generated by gen-accessors; DO NOT EDIT.

package properties

// GetExpression returns the Expression field if it's non-nil, zero value otherwise.
func (m *MultiDimensional) GetExpression() string {
	if m == nil || m.Expression == nil {
		return ""
	}
	return *m.Expression
}

// GetIndex returns the Index field if it's non-nil, zero value otherwise.
func (m *MultiDimensional) GetIndex() int {
	if m == nil || m.Index == nil {
		return 0
	}
	return *m.Index
}

// GetExpression returns the Expression field if it's non-nil, zero value otherwise.
func (m *MultiDimensionalKeyframed) GetExpression() string {
	if m == nil || m.Expression == nil {
		return ""
	}
	return *m.Expression
}

// GetIndex returns the Index field if it's non-nil, zero value otherwise.
func (m *MultiDimensionalKeyframed) GetIndex() int {
	if m == nil || m.Index == nil {
		return 0
	}
	return *m.Index
}

// GetIn returns the In field.
func (o *OffsetKeyframe) GetIn() *In {
	if o == nil {
		return nil
	}
	return o.In
}

// GetOut returns the Out field.
func (o *OffsetKeyframe) GetOut() *Out {
	if o == nil {
		return nil
	}
	return o.Out
}

// GetStartTime returns the StartTime field if it's non-nil, zero value otherwise.
func (o *OffsetKeyframe) GetStartTime() float64 {
	if o == nil || o.StartTime == nil {
		return 0.0
	}
	return *o.StartTime
}

// GetExpression returns the Expression field if it's non-nil, zero value otherwise.
func (v *Value) GetExpression() string {
	if v == nil || v.Expression == nil {
		return ""
	}
	return *v.Expression
}

// GetIndex returns the Index field if it's non-nil, zero value otherwise.
func (v *Value) GetIndex() int {
	if v == nil || v.Index == nil {
		return 0
	}
	return *v.Index
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (v *Value) GetValue() float64 {
	if v == nil || v.Value == nil {
		return 0.0
	}
	return *v.Value
}

// GetIn returns the In field.
func (v *ValueKeyframe) GetIn() *In {
	if v == nil {
		return nil
	}
	return v.In
}

// GetOut returns the Out field.
func (v *ValueKeyframe) GetOut() *Out {
	if v == nil {
		return nil
	}
	return v.Out
}

// GetStartTime returns the StartTime field if it's non-nil, zero value otherwise.
func (v *ValueKeyframe) GetStartTime() float64 {
	if v == nil || v.StartTime == nil {
		return 0.0
	}
	return *v.StartTime
}

// GetExpression returns the Expression field if it's non-nil, zero value otherwise.
func (v *ValueKeyframed) GetExpression() string {
	if v == nil || v.Expression == nil {
		return ""
	}
	return *v.Expression
}

// GetIndex returns the Index field if it's non-nil, zero value otherwise.
func (v *ValueKeyframed) GetIndex() int {
	if v == nil || v.Index == nil {
		return 0
	}
	return *v.Index
}
